name: Deploy lambda

on:
  push:
    branches: [ mainline ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Python packages
      run: |
        python -m pip install boto3
    - name: Deploy to AWS Lambda
      run: |
        python deploy_scripts/deploy_lambda.py \
          --lambda-function=XGBoostCICostWatcher --code-dir=cost_watcher
        python deploy_scripts/deploy_lambda.py \
          --lambda-function=XGBoostCIS3Monitor --code-dir=s3_monitor
        python deploy_scripts/deploy_lambda.py \
          --lambda-function=XGBoostCIEC2Monitor --code-dir=ec2_monitor
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
