name: Deploy lambda

on:
  push:
    branches: [ mainline ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Python packages
      run: |
        python -m pip install boto3 requests
    - name: Deploy code package to AWS Lambda
      run: |
        cd autoscaler
        python deploy.py
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
